//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0-rc.13

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "Kiosk")]
pub struct Model {
    #[sea_orm(
        column_name = "kioskOwnercap",
        primary_key,
        auto_increment = false,
        column_type = "Text",
        unique
    )]
    pub kiosk_ownercap: String,
    #[sea_orm(primary_key, auto_increment = false, column_type = "Text")]
    pub kiosk: String,
    pub personal: bool,
    #[sea_orm(column_name = "ownerWalletAddress", column_type = "Text")]
    pub owner_wallet_address: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::wallet::Entity",
        from = "Column::OwnerWalletAddress",
        to = "super::wallet::Column::Address",
        on_update = "Cascade",
        on_delete = "Restrict"
    )]
    Wallet,
}

impl Related<super::wallet::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Wallet.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
