//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0-rc.13

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "LaunchpadCollection")]
pub struct Model {
    #[sea_orm(
        column_name = "collectionType",
        primary_key,
        auto_increment = false,
        column_type = "Text"
    )]
    pub collection_type: String,
    #[sea_orm(column_name = "kioskStandard")]
    pub kiosk_standard: bool,
    #[sea_orm(column_type = "Text")]
    pub name: String,
    #[sea_orm(column_type = "Text")]
    pub description: String,
    #[sea_orm(column_type = "Text")]
    pub supply: String,
    pub price: i64,
    #[sea_orm(column_name = "maxItemPerAddress", column_type = "Text")]
    pub max_item_per_address: String,
    #[sea_orm(column_name = "whiteListEnabled")]
    pub white_list_enabled: bool,
    #[sea_orm(column_name = "whiteListPrice")]
    pub white_list_price: i64,
    #[sea_orm(column_name = "whiteListSupply", column_type = "Text")]
    pub white_list_supply: String,
    #[sea_orm(column_name = "customEnabled")]
    pub custom_enabled: bool,
    #[sea_orm(column_name = "customName", column_type = "Text")]
    pub custom_name: String,
    #[sea_orm(column_name = "customPrice")]
    pub custom_price: i64,
    #[sea_orm(column_name = "customSupply", column_type = "Text")]
    pub custom_supply: String,
    #[sea_orm(column_name = "mintCount")]
    pub mint_count: i32,
    #[sea_orm(column_name = "createdAt")]
    pub created_at: DateTime,
    #[sea_orm(column_name = "updatedAt")]
    pub updated_at: DateTime,
    #[sea_orm(column_name = "creatorCap", column_type = "Text")]
    pub creator_cap: String,
    #[sea_orm(column_name = "launchId", column_type = "Text", unique)]
    pub launch_id: String,
    pub native: bool,
    #[sea_orm(column_type = "Text")]
    pub state: String,
    #[sea_orm(column_name = "coverImage", column_type = "Text", nullable)]
    pub cover_image: Option<String>,
    #[sea_orm(column_name = "startTime")]
    pub start_time: DateTime,
    #[sea_orm(column_name = "whiteListStartTime")]
    pub white_list_start_time: DateTime,
    #[sea_orm(column_name = "customStartTime")]
    pub custom_start_time: DateTime,
    #[sea_orm(column_name = "ownerWalletAddress", column_type = "Text")]
    pub owner_wallet_address: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::wallet::Entity",
        from = "Column::OwnerWalletAddress",
        to = "super::wallet::Column::Address",
        on_update = "Cascade",
        on_delete = "Restrict"
    )]
    Wallet,
    #[sea_orm(has_many = "super::white_list_address::Entity")]
    WhiteListAddress,
}

impl Related<super::wallet::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Wallet.def()
    }
}

impl Related<super::white_list_address::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::WhiteListAddress.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
